version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: techfeed-postgres
    environment:
      POSTGRES_DB: techfeed_hub
      POSTGRES_USER: techfeed_user
      POSTGRES_PASSWORD: techfeed_password
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/conf:/etc/postgresql
    networks:
      - techfeed-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techfeed_user -d techfeed_hub"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: techfeed-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - techfeed-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  techfeed-network:
    driver: bridge